import Head from "next/head";
import HeroSection from "@/component/Home/HeroSection/HeroSection";
import Event from "@/component/Home/Event/Event";
import About from "@/component/Home/About/About";
import Advisor from "@/component/Home/Advisor/Advisor";
import Cabinet from "@/component/Home/Cabinet/Cabinet";
import Heads from "@/component/Home/Heads/Head";
import MainLayout from "@/Layout/MainLayout/MainLayout";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <HeroSection />
        <About/>
        <Advisor/>
        <Cabinet />
        <Heads />
        <Event />
      </MainLayout>
    </>
  );
}
